import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    height: Platform.OS === 'ios' ? 110 : 90,
    justifyContent: 'flex-end',
    paddingBottom: 15,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: '700' },
  backBtn: { padding: 4 },
  formContainer: { paddingHorizontal: 25, paddingTop: 25, paddingBottom: 60 },
  inputWrapper: { marginBottom: 18 },
  label: {
    fontSize: 11,
    marginBottom: 6,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  mainInput: { flex: 1, fontSize: 16, fontWeight: '600', paddingVertical: 0 },
  row: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  totalDisplay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 5,
  },
  totalLabel: { fontSize: 14, fontWeight: '600' },
  totalAmount: { fontSize: 20, fontWeight: '800' },
  addToListBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 20,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    marginBottom: 25,
    gap: 8,
  },
  addToListText: { fontWeight: '700', fontSize: 14 },
  batchContainer: { marginBottom: 25 },
  batchTitle: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  batchScroll: { flexDirection: 'row' },
  batchCard: {
    width: 130,
    padding: 12,
    borderRadius: 18,
    marginRight: 12,
    borderWidth: 1.5,
  },
  batchCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  batchAmount: { fontSize: 14, fontWeight: '800', flex: 1, marginRight: 4 },
  batchNote: { fontSize: 12, fontWeight: '600' },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 60,
    borderRadius: 20,
    gap: 12,
    elevation: 4,
    overflow: 'hidden',
  },
  saveText: { color: '#fff', fontSize: 16, fontWeight: '800' },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  modalAlertBox: {
    width: '100%',
    borderRadius: 24,
    padding: 25,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  alertIconContainer: { marginBottom: 15 },
  modalAlertTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalAlertMessage: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 22,
    lineHeight: 20,
  },
  modalAlertBtn: {
    width: '100%',
    height: 48,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalAlertBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
});