import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerGradient: {
    height: 350,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    paddingTop: 50,
    position: 'relative',
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  titleArea: { flex: 1 },
  greetingContainer: { height: 25, overflow: 'hidden', marginBottom: 2 },
  bellBtn: {
    width: 45,
    height: 45,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notiBadge: {
    position: 'absolute',
    right: -2,
    top: -2,
    backgroundColor: '#FF3B30',
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
  },
  incomingNotiBox: {
    position: 'absolute',
    top: 20,
    left: 30,
    right: 30,
    zIndex: 1000,
  },
  notiInnerRow: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  notiCloseBtn: {
    padding: 5,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 12,
  },
  progressBarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  progressBar: {
    height: '100%',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 3,
  },
  notiBlur: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 25,
    gap: 10,
    overflow: 'hidden',
    backgroundColor: 'rgba(15,23,42,0.85)',
    borderWidth: 1,
    minHeight: 40,
    maxHeight: 120,
  },
  notiIconCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#F59E0B',
    marginLeft: -6,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  incomingNotiText: { fontSize: 12, flex: 1, fontWeight: '500' },
  welcomeText: { opacity: 0.9, fontSize: 14, fontWeight: '500', height: 25 },
  subGreeting: { fontSize: 12, height: 25, fontWeight: '500' },
  guestText: { fontSize: 24, fontWeight: 'bold' },
  balanceCardWrapper: {
    borderRadius: 28,
    marginTop: 17,
    overflow: 'hidden',
    borderWidth: 1,
  },
  balanceCard: { padding: 20 },
  balanceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  iconBg: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  balanceLabel: { fontSize: 16, fontWeight: '500' },
  balanceAmount: { fontSize: 32, fontWeight: 'bold' },
  currencyText: { fontSize: 18 },
  statsRow: {
    flexDirection: 'row',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
  },
  statItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
  },
  statText: { fontSize: 13, fontWeight: '600' },
  separator: { width: 1, height: '100%' },
  contentArea: { flex: 1, paddingHorizontal: 20 },
});