import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    height: Platform.OS === 'ios' ? 110 : 90,
    justifyContent: 'flex-end',
    paddingBottom: 15,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: '700' },
  backBtn: { padding: 4 },
  formContainer: { paddingHorizontal: 25, paddingTop: 25, paddingBottom: 60 },
  switcherContainer: { marginBottom: 10, alignItems: 'center' },
  switcherBackground: { flexDirection: 'row', padding: 4, borderRadius: 22, width: '100%' },
  switchBtn: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: 18 },
  activeExpense: { backgroundColor: '#EF4444' },
  activeIncome: { backgroundColor: '#10B981' },
  switchText: { fontSize: 14, fontWeight: '700' },
  inputWrapper: { marginBottom: 18 },
  label: {
    fontSize: 11,
    marginBottom: 6,
    marginTop: 4,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  inputBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  currencySymbol: { fontSize: 20, marginRight: 10, fontWeight: '700' },
  amountInput: { flex: 1, fontSize: 24, fontWeight: '700', paddingVertical: 0 },
  row: { flexDirection: 'row', gap: 12, marginBottom: 15 },
  iconBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 20,
    gap: 10,
    borderWidth: 1.5,
  },
  boxText: { fontSize: 14, fontWeight: '600' },
  noteBox: {
    flexDirection: 'row',
    padding: 15,
    borderRadius: 20,
    borderWidth: 1.5,
    minHeight: 80,
  },
  noteInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    textAlignVertical: 'top',
    paddingVertical: 0,
  },
  addToListBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    borderRadius: 15,
    borderStyle: 'dashed',
    borderWidth: 1.5,
    marginBottom: 20,
    gap: 8,
  },
  addToListText: { fontWeight: '700', fontSize: 14 },
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 60,
    borderRadius: 20,
    gap: 12,
    elevation: 4,
    overflow: 'hidden',
  },
  saveText: { color: '#fff', fontSize: 16, fontWeight: '800' },

  batchContainer: { marginBottom: 25 },
  batchTitle: {
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  batchScroll: { flexDirection: 'row' },
  batchCard: {
    width: 130,
    padding: 12,
    borderRadius: 18,
    marginRight: 12,
    borderWidth: 1.5,
  },
  batchCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  batchAmount: { fontSize: 14, fontWeight: '800', flex: 1, marginRight: 4 },
  batchNote: { fontSize: 12, fontWeight: '600' },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  modalAlertBox: {
    width: '100%',
    borderRadius: 24,
    padding: 25,
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  alertIconContainer: { marginBottom: 15 },
  modalAlertTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalAlertMessage: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 22,
    lineHeight: 20,
  },
  modalAlertBtn: {
    width: '100%',
    height: 48,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalAlertBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
});