import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, paddingBottom: 35 },
  header: {
    paddingTop: 45,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  screenHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 12,
    width: '100%',
  },
  screenHeaderTitleText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  modalActionRow: {
    flexDirection: 'row',
    width: '100%',
    gap: 15,
  },
  cardPrimaryBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardSecondaryBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#eee',
  },
  modalOverlayBottom: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalOverlayCenter: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerCardWrapper: { width: '82%', alignItems: 'center' },
  pinCard: {
    width: '100%',
    borderRadius: 30,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  cardIconBg: {
    width: 60,
    height: 60,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  cardSubTitle: {
    fontSize: 13,
    color: '#999',
    marginBottom: 10,
    textAlign: 'center',
  },
  bottomSheet: {
    width: '100%',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    padding: 25,
    paddingBottom: 40,
  },
  sheetHandle: {
    width: 45,
    height: 5,
    backgroundColor: '#E0E0E0',
    borderRadius: 10,
    alignSelf: 'center',
    marginBottom: 20,
  },
  passInput: {
    width: '80%',
    fontSize: 32,
    textAlign: 'center',
    borderBottomWidth: 2,
    paddingBottom: 10,
    letterSpacing: 15,
    marginBottom: 20,
  },
  modalMainTitle: { fontSize: 19, fontWeight: 'bold', textAlign: 'center' },
  menuOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    gap: 15,
  },
  menuText: { fontSize: 16, fontWeight: '500' },
  removeBtn: {
    width: '100%',
    padding: 16,
    backgroundColor: '#FF6B6B',
    borderRadius: 15,
    alignItems: 'center',
    marginTop: 10,
  },
  modalOverlayResetData: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  dangerIconBg: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionCard: {
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 25,
    padding: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 15,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  profileInfo: { flexDirection: 'row', alignItems: 'center', gap: 15 },
  avatarContainer: {
    width: 70,
    height: 70,
    borderRadius: 25,
    borderWidth: 2,
  },
  userName: { fontSize: 20, fontWeight: 'bold' },
  syncStatus: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 5 },
  syncText: { fontSize: 12, fontWeight: '600' },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
  },
  rowLeft: { flexDirection: 'row', alignItems: 'center', gap: 15 },
  iconContainer: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowLabel: { fontSize: 16, fontWeight: '500' },
  rowRight: { flexDirection: 'row', alignItems: 'center' },
  valueRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  rowValue: { fontSize: 14 },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSheetReset: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 30,
    alignItems: 'center',
  },
  dangerIconAnim: {
    width: 60,
    height: 60,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalIconBg: {
    width: 70,
    height: 70,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalSubTitle: {
    fontSize: 14,
    color: '#999',
    marginBottom: 25,
    textAlign: 'center',
  },
  actionBtn: {
    width: '100%',
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: 'center',
    marginBottom: 15,
  },
  actionBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  cancelBtn: { padding: 10 },
  alertBox: {
    width: width * 0.8,
    borderRadius: 25,
    padding: 25,
    alignItems: 'center',
  },
  alertCloseBtn: {
    width: '100%',
    paddingVertical: 12,
    borderRadius: 15,
    alignItems: 'center',
  },
  notiSheet: {
    width: '100%',
    height: '80%',
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 25,
  },
  notiHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  inputWrapper: { marginBottom: 25 },
  notiInput: {
    borderWidth: 1,
    borderRadius: 15,
    padding: 15,
    height: 100,
    textAlignVertical: 'top',
    marginBottom: 15,
  },
  sendBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 15,
    gap: 10,
  },
  sendBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  historyTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee',
  },
  historyText: { flex: 1, fontSize: 14 },
  historyTime: { fontSize: 11, color: '#999' },
  emptyHistory: { textAlign: 'center', marginTop: 20, color: '#999' },
  aboutLogo: { width: 80, height: 80, borderRadius: 20, marginBottom: 15 },
  aboutAppName: { fontSize: 22, fontWeight: 'bold' },
  devTag: {
    marginTop: 15,
    paddingHorizontal: 15,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: 'rgba(150,150,150,0.05)',
  },
});